version: '3'
services:
    nginx:
        image: nginx:1.18.0
        container_name: ngx01
        ports:
            - "8000:8000"
        volumes:
            - ./nginx/:/etc/nginx/
        depends_on:
            - django
        networks:
            - website_network
        restart: unless-stopped
    #   log-driver: "syslog"
    #       log_opt:
    #           address: elasticsearch:9200
    
    django:
        build:
            context: ./django
        container_name: djg01
        volumes:
            - ./django/website:/srv/website
        expose:
            - "8000"
        depends_on:
            - postgres
        environments:
            - DJANGO_PROJECT_NAME=website
        restart: unless-stopped
    #   log-driver: "syslog"
    #       log_opt:
    #           address: elasticsearch:9200
    
    postgres:
        image: postgres:12.2
        container_name: psg01
        volumes:
            - ./postgres:/var/lib/postgresql/data/pgdata
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_NAME=postgres
            - POSTGRES_NAME=postgres
            - POSTGRES_PASSWORD=totallysecurepassword
            - PGDATA=pgdata
        networks:
            - website_network
        restart: unless-stopped
    #   log-driver: "syslog"
    #       log_opt:
    #           address: elasticsearch:9200
    
    #elasticsearch:
    #    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    #    container_name: els01
    #    hostname: elasticsearch
    #    networks:
    #      - website_network
    #    volumes:
    #      - elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #    ports:
    #      - "9200:9200"
    #      - "9300:9300"
    #    restart: unless-stopped
    #    environment:
    #      - transport.host=127.0.0.1
    #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #    ulimits:
    #      memlock:
    #        soft: -1
    #        hard: -1
    #    mem_limit: 1g

    #kibana:
    #    image: docker.elastic.co/kibana/kibana:6.5.3
    #    container_name: kib01
    #    hostname: kibana
    #    volumes:
    #      - kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    #    ports:
    #      - "5601:5601"
    #    restart: unless-stopped
    #    networks:
    #      - website_network
    #    depends_on:
    #      - elasticsearch


networks:
    website_network:
        driver: bridge